from __future__ import annotations
from app.models.user import User
from app.models.hospital import Hospital
from app.models.baby import Baby
from app.models.exam import Exam
from app.models.appointment import Appointment
from app.models.reminder import Reminder
from app.models.alert import Alert
from app.models.outcome import Outcome
from app.models.referral import Referral
